version: '3.1'
services:
  app:
    container_name: travel-agent
    image: travel-agent
    build: ./
    ports:
    - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
    - "54320:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
